services:
  # MySQL Database Container
  mysql-db:
    image: mysql:8.0
    container_name: banking-mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: bank_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_bank_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - banking-network

  # Spring Boot Application Container
  banking-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: banking-backend-app
    restart: always
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      DB_URL: jdbc:mysql://mysql-db:3306/bank_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION_MS: 86400000
    ports:
      - "8080:8080"
    networks:
      - banking-network

networks:
  banking-network:
    driver: bridge

volumes:
  mysql_bank_data:
    driver: local
